### PR TITLE
add Colombian departments broken down

### PR DESCRIPTION
**Pull request by CamilaAchuri**
Agregué el topojson de cada depto de colombia

### CODE REVIEW

**Comment by jpmarindiaz** [comment]
@CamilaAchury Do we really need individual topojsons for each department? Isn't there a way to filter each department on the fly?

**Comment by lenafm** [comment]
@jpmarindiaz  If I understand `lfltmagic` correctly we'd need to introduce an extra parameter to subset an existing map in order to do it on the fly, but I could be wrong.

@CamilaAchury I just checked out this PR locally to run the tests but my computer is having problems with the encoding (as usual) of the file names of the departments when they have tildes (nariño). I think it might be good to have the filenames without any accents/tildes, what do you think?

**Comment by jpmarindiaz** [comment]
@CamilaAchury never name files with tildes and weird accents
@lenafm Correct, it would be better to have a parameter to filter the topojson on the fly. Not only we need single deparments (or subregions) but we could also have a list of subregions, say the departments of the Eje Cafetero in Colombia, in that case we would filter by a list of region ids

**Comment by lenafm** [comment]
@jpmarindiaz I suggest I merge this for now (I imagine @CamilaAchury wants to use this for something specific?) and we add it as issues to `geodata` and `lfltmagic` to make the change with the parameters?

**Comment by jpmarindiaz** [comment]
yes

**Comment by lenafm** [comment]
Okay, @CamilaAchury could you change the file names so none of them include any tildes/weird accents? Will merge after that :)

**Comment by CamilaAchuri** [comment]
Ahí lo ajuste, lo hice así mientras tanto porque a pesar que lo intente hacer como @jpmarindiaz dice, (filtrando directamente) no la logré y tengo prisa con esto, porque es lo del CNE, después podemos discutir los problemas que encontré al intentar filtrarlo desde leaflet, porque no funciona de la misma forma como se puede hacer en ggplot.

**Pull request merged**
